### ISSUE TITLE
cannot install

### ISSUE THREAD

**Issue by runm717123** [alexZajac/react-native-skeleton-content-nonexpo#3]
![image](https://user-images.githubusercontent.com/33694392/70955700-5de16780-20a4-11ea-85b2-1c8354383a5b.png)

**Comment by alexZajac** [comment]
Hey @runm717123 ! 
This issue is happening because a .git repository is present in your version of `react-native-safe-area-view` (see [this](https://github.com/react-native-community/react-native-safe-area-view/issues/69)). It's not related to `react-native-skeleton-content-nonexpo`, follow the github issus I gave you to solve it (removing .git folder for `react-native-safe-area-view` and reinstalling latest version).
